-- This file contains SQL commands that will be emitted in test and dev.
-- Ticket sample data for testing and development

INSERT INTO Ticket (id, title, description) VALUES (1, 'Login page not loading', 'Users are unable to access the login page. The page appears to be stuck on loading and eventually times out.');
INSERT INTO Ticket (id, title, description) VALUES (2, 'Database connection timeout', 'Application is experiencing intermittent database connection timeouts during peak hours.');
INSERT INTO Ticket (id, title, description) VALUES (3, 'Email notifications not sending', 'System is not sending automated email notifications for password resets and account confirmations.');
INSERT INTO Ticket (id, title, description) VALUES (4, 'Mobile app crashes on startup', 'iOS application crashes immediately after opening on devices running iOS 16 and above.');
INSERT INTO Ticket (id, title, description) VALUES (5, 'Search functionality returns no results', 'The search feature is not returning any results even for queries that should have matches.');
INSERT INTO Ticket (id, title, description) VALUES (6, 'Payment processing errors', 'Credit card payments are failing with error code 500. Payment gateway integration needs investigation.');
INSERT INTO Ticket (id, title, description) VALUES (7, 'User profile images not displaying', 'Profile pictures uploaded by users are not showing in the user interface.');
INSERT INTO Ticket (id, title, description) VALUES (8, 'API response time is slow', 'REST API endpoints are responding slowly, taking over 5 seconds for simple requests.');
INSERT INTO Ticket (id, title, description) VALUES (9, 'File upload feature broken', 'Users cannot upload files larger than 1MB. The upload process fails without error messages.');
INSERT INTO Ticket (id, title, description) VALUES (10, 'Dashboard widgets not loading', 'The main dashboard widgets are not loading data and showing empty states.');
INSERT INTO Ticket (id, title, description) VALUES (11, 'Password reset link expired', 'Password reset links are expiring immediately after being generated.');
INSERT INTO Ticket (id, title, description) VALUES (12, 'Shopping cart items disappearing', 'Items added to shopping cart are disappearing when users navigate to other pages.');
INSERT INTO Ticket (id, title, description) VALUES (13, 'SSL certificate renewal needed', 'SSL certificate expires in 7 days and needs to be renewed to maintain secure connections.');
INSERT INTO Ticket (id, title, description) VALUES (14, 'Memory leak in background service', 'Background processing service is consuming increasing amounts of memory over time.');
INSERT INTO Ticket (id, title, description) VALUES (15, 'Report generation failing', 'Monthly reports are failing to generate with insufficient memory error.');
INSERT INTO Ticket (id, title, description) VALUES (16, 'Two-factor authentication bypass', 'Security vulnerability allows bypassing 2FA under certain conditions.');
INSERT INTO Ticket (id, title, description) VALUES (17, 'Dark mode toggle not working', 'The dark mode toggle in user preferences is not applying the theme changes.');
INSERT INTO Ticket (id, title, description) VALUES (18, 'Backup process incomplete', 'Automated daily backups are failing to complete and only partial data is being backed up.');
INSERT INTO Ticket (id, title, description) VALUES (19, 'Notification sounds not playing', 'Push notification sounds are not playing on desktop browsers.');
INSERT INTO Ticket (id, title, description) VALUES (20, 'Calendar integration broken', 'Calendar synchronization with external services has stopped working.');
INSERT INTO Ticket (id, title, description) VALUES (21, 'User session timeout too short', 'Users are being logged out every 5 minutes, which is too frequent for normal usage.');
INSERT INTO Ticket (id, title, description) VALUES (22, 'Excel export formatting issues', 'Data exported to Excel format has incorrect formatting and missing columns.');
INSERT INTO Ticket (id, title, description) VALUES (23, 'Video playback stuttering', 'Video content is stuttering and buffering excessively on all browsers.');
INSERT INTO Ticket (id, title, description) VALUES (24, 'Breadcrumb navigation incorrect', 'Breadcrumb navigation is showing incorrect page hierarchy and broken links.');
INSERT INTO Ticket (id, title, description) VALUES (25, 'Form validation not working', 'Client-side form validation is not preventing submission of invalid data.');
INSERT INTO Ticket (id, title, description) VALUES (26, 'Chat feature offline', 'Live chat functionality is showing as offline even when support agents are available.');
INSERT INTO Ticket (id, title, description) VALUES (27, 'Image compression quality poor', 'Uploaded images are being compressed too aggressively, resulting in poor quality.');
INSERT INTO Ticket (id, title, description) VALUES (28, 'Timezone conversion errors', 'Date and time displays are not properly converting to user''s local timezone.');
INSERT INTO Ticket (id, title, description) VALUES (29, 'Bulk operations timing out', 'Bulk delete and update operations are timing out for datasets larger than 1000 records.');
INSERT INTO Ticket (id, title, description) VALUES (30, 'Autocomplete suggestions outdated', 'Search autocomplete is showing outdated suggestions that no longer match current data.');
INSERT INTO Ticket (id, title, description) VALUES (31, 'Responsive design broken on tablets', 'Website layout is broken on tablet devices in portrait orientation.');
INSERT INTO Ticket (id, title, description) VALUES (32, 'Email template rendering issues', 'HTML email templates are not rendering properly in Outlook clients.');
INSERT INTO Ticket (id, title, description) VALUES (33, 'Cache invalidation problems', 'Application cache is not invalidating properly, showing stale data to users.');
INSERT INTO Ticket (id, title, description) VALUES (34, 'Sorting functionality inconsistent', 'Table sorting is producing inconsistent results across different data types.');
INSERT INTO Ticket (id, title, description) VALUES (35, 'WebSocket connection drops', 'Real-time features lose connection frequently, requiring page refresh.');
INSERT INTO Ticket (id, title, description) VALUES (36, 'PDF generation memory issues', 'Large PDF reports are causing out-of-memory errors during generation.');
INSERT INTO Ticket (id, title, description) VALUES (37, 'Language translation incomplete', 'Several UI elements are not translated in the French language pack.');
INSERT INTO Ticket (id, title, description) VALUES (38, 'Data synchronization delays', 'Data sync between mobile app and server is delayed by several minutes.');
INSERT INTO Ticket (id, title, description) VALUES (39, 'Cross-browser compatibility issues', 'Application features work in Chrome but fail in Firefox and Safari.');
INSERT INTO Ticket (id, title, description) VALUES (40, 'Audit log entries missing', 'Security audit logs are missing entries for user login and logout events.');
INSERT INTO Ticket (id, title, description) VALUES (41, 'Performance monitoring alerts', 'Application response time has exceeded acceptable thresholds for the past 2 hours.');
INSERT INTO Ticket (id, title, description) VALUES (42, 'Third-party API rate limiting', 'External API calls are being rate limited, causing feature degradation.');
INSERT INTO Ticket (id, title, description) VALUES (43, 'Database schema migration failed', 'Latest database migration script failed to execute, leaving schema in inconsistent state.');
INSERT INTO Ticket (id, title, description) VALUES (44, 'Load balancer configuration issue', 'Traffic is not being distributed evenly across application servers.');
INSERT INTO Ticket (id, title, description) VALUES (45, 'Cookie consent banner broken', 'GDPR cookie consent banner is not appearing on the website.');
INSERT INTO Ticket (id, title, description) VALUES (46, 'Print stylesheet missing styles', 'Printed pages are missing important styling and layout information.');
INSERT INTO Ticket (id, title, description) VALUES (47, 'Dropdown menu positioning wrong', 'Dropdown menus are appearing off-screen on smaller browser windows.');
INSERT INTO Ticket (id, title, description) VALUES (48, 'Background job queue stuck', 'Background job processing queue has stopped processing new jobs.');
INSERT INTO Ticket (id, title, description) VALUES (49, 'Content delivery network slow', 'CDN is serving static assets slowly, impacting page load times.');
INSERT INTO Ticket (id, title, description) VALUES (50, 'User permission escalation bug', 'Regular users can access admin functions through URL manipulation.');
INSERT INTO Ticket (id, title, description) VALUES (51, 'Widget configuration not saving', 'Dashboard widget configuration changes are not being persisted.');
INSERT INTO Ticket (id, title, description) VALUES (52, 'Search results pagination broken', 'Search result pagination is showing incorrect page numbers and counts.');
INSERT INTO Ticket (id, title, description) VALUES (53, 'File preview thumbnails missing', 'Document and image thumbnails are not generating for uploaded files.');
INSERT INTO Ticket (id, title, description) VALUES (54, 'Social media login failing', 'OAuth login through Facebook and Google accounts is returning authentication errors.');
INSERT INTO Ticket (id, title, description) VALUES (55, 'Inventory count discrepancies', 'Product inventory counts are not matching between warehouse and system records.');
INSERT INTO Ticket (id, title, description) VALUES (56, 'Map integration not loading', 'Google Maps integration on location pages is showing blank map containers.');
INSERT INTO Ticket (id, title, description) VALUES (57, 'Keyboard navigation broken', 'Tab navigation through form elements is skipping required fields.');
INSERT INTO Ticket (id, title, description) VALUES (58, 'Data export timeout errors', 'Large dataset exports are timing out before completion.');
INSERT INTO Ticket (id, title, description) VALUES (59, 'Color contrast accessibility issue', 'Text color contrast does not meet WCAG accessibility guidelines.');
INSERT INTO Ticket (id, title, description) VALUES (60, 'Duplicate record creation bug', 'System is creating duplicate records when users double-click submit buttons.');
INSERT INTO Ticket (id, title, description) VALUES (61, 'Session management vulnerability', 'User sessions are not properly invalidated after logout.');
INSERT INTO Ticket (id, title, description) VALUES (62, 'Batch processing performance', 'Nightly batch jobs are taking longer than the allocated maintenance window.');
INSERT INTO Ticket (id, title, description) VALUES (63, 'URL routing case sensitivity', 'Application URLs are case-sensitive causing 404 errors for valid pages.');
INSERT INTO Ticket (id, title, description) VALUES (64, 'Progress indicator not updating', 'File upload progress bars are stuck at 0% even during successful uploads.');
INSERT INTO Ticket (id, title, description) VALUES (65, 'Configuration file permissions', 'Application configuration files have incorrect permissions causing startup failures.');
INSERT INTO Ticket (id, title, description) VALUES (66, 'Health check endpoint failing', 'Application health check is returning unhealthy status intermittently.');
INSERT INTO Ticket (id, title, description) VALUES (67, 'Custom field validation missing', 'User-defined custom fields are not being validated according to their type rules.');
INSERT INTO Ticket (id, title, description) VALUES (68, 'Notification delivery delays', 'Push notifications are being delivered with significant delays.');
INSERT INTO Ticket (id, title, description) VALUES (69, 'Browser back button issues', 'Using browser back button causes form data loss and navigation errors.');
INSERT INTO Ticket (id, title, description) VALUES (70, 'API versioning conflicts', 'Different API versions are returning inconsistent data formats.');
INSERT INTO Ticket (id, title, description) VALUES (71, 'Log rotation not working', 'Application log files are growing without rotation, consuming disk space.');
INSERT INTO Ticket (id, title, description) VALUES (72, 'Tooltip positioning incorrect', 'Help tooltips are appearing off-screen and overlapping content.');
INSERT INTO Ticket (id, title, description) VALUES (73, 'Concurrent user limit reached', 'System is rejecting new user logins due to concurrent user limitations.');
INSERT INTO Ticket (id, title, description) VALUES (74, 'Data validation bypass possible', 'Server-side validation can be bypassed by modifying client requests.');
INSERT INTO Ticket (id, title, description) VALUES (75, 'Backup restoration testing needed', 'Monthly backup restoration test has not been performed this quarter.');
INSERT INTO Ticket (id, title, description) VALUES (76, 'Mobile keyboard overlay issue', 'Virtual keyboard on mobile devices is covering input fields.');
INSERT INTO Ticket (id, title, description) VALUES (77, 'Cron job scheduling conflict', 'Multiple scheduled tasks are running simultaneously, causing resource conflicts.');
INSERT INTO Ticket (id, title, description) VALUES (78, 'User interface freezing', 'Application UI becomes unresponsive during large data loading operations.');
INSERT INTO Ticket (id, title, description) VALUES (79, 'Error message localization', 'System error messages are not being translated to user''s selected language.');
INSERT INTO Ticket (id, title, description) VALUES (80, 'Cookie expiration handling', 'Authentication cookies are not handling expiration gracefully.');
INSERT INTO Ticket (id, title, description) VALUES (81, 'Nested dropdown menu issues', 'Multi-level dropdown menus are not staying open when hovering over submenus.');
INSERT INTO Ticket (id, title, description) VALUES (82, 'File type restriction bypass', 'File upload restrictions can be bypassed by changing file extensions.');
INSERT INTO Ticket (id, title, description) VALUES (83, 'Analytics tracking incomplete', 'User behavior analytics are missing data for mobile app interactions.');
INSERT INTO Ticket (id, title, description) VALUES (84, 'Content security policy errors', 'CSP violations are being logged for legitimate application resources.');
INSERT INTO Ticket (id, title, description) VALUES (85, 'Database connection pool exhaustion', 'Application is exhausting database connection pool during peak usage.');
INSERT INTO Ticket (id, title, description) VALUES (86, 'Lazy loading not working', 'Image lazy loading is not functioning, causing slow page loads.');
INSERT INTO Ticket (id, title, description) VALUES (87, 'Feature flag rollout issues', 'Feature flags are not properly controlling new feature visibility.');
INSERT INTO Ticket (id, title, description) VALUES (88, 'Sitemap generation outdated', 'XML sitemap is not including newly created pages and content.');
INSERT INTO Ticket (id, title, description) VALUES (89, 'Cross-site scripting vulnerability', 'XSS vulnerability found in user comment submission form.');
INSERT INTO Ticket (id, title, description) VALUES (90, 'Memory usage optimization needed', 'Application memory usage has increased significantly after recent updates.');
INSERT INTO Ticket (id, title, description) VALUES (91, 'Infinite scroll performance issue', 'Infinite scroll feature becomes sluggish after loading many items.');
INSERT INTO Ticket (id, title, description) VALUES (92, 'Webhook delivery failures', 'Outbound webhooks are failing to deliver to external systems.');
INSERT INTO Ticket (id, title, description) VALUES (93, 'Input sanitization incomplete', 'User input sanitization is missing for certain form fields.');
INSERT INTO Ticket (id, title, description) VALUES (94, 'Cache warming strategy needed', 'Application cache needs warming strategy to improve cold start performance.');
INSERT INTO Ticket (id, title, description) VALUES (95, 'Modal dialog accessibility', 'Modal dialogs are not properly managing keyboard focus for screen readers.');
INSERT INTO Ticket (id, title, description) VALUES (96, 'Rate limiting too aggressive', 'API rate limiting is blocking legitimate user requests too frequently.');
INSERT INTO Ticket (id, title, description) VALUES (97, 'Scheduled maintenance notification', 'Users are not receiving adequate notice of scheduled maintenance windows.');
INSERT INTO Ticket (id, title, description) VALUES (98, 'Data archival process failing', 'Automated data archival process is failing to move old records to archive storage.');
INSERT INTO Ticket (id, title, description) VALUES (99, 'Plugin compatibility issues', 'Third-party plugins are causing conflicts with core application functionality.');
INSERT INTO Ticket (id, title, description) VALUES (100, 'Performance regression detected', 'Latest deployment has introduced performance regressions across multiple endpoints.');

-- Reset sequence to continue from 101
ALTER SEQUENCE ticket_seq RESTART WITH 101;