apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-api-demo.fullname" . }}-postgres
  labels:
    {{- include "mcp-api-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}